### ISSUE TITLE
option --iterations does not work with "-1" ("infinite") value

### ISSUE THREAD

**Issue by llivejo** [strizhechenko/netutils-linux#101]
Command-line option "--iterations" doesn't work as intended.

  -n ITERATIONS, --iterations=ITERATIONS
  Count of screen's renews, -1 - infinite loop.

$ time network-top -n -1
real	0m0.070s
user	0m0.040s
sys	0m0.028s

(immediate exit)

**Comment by strizhechenko** [comment]
Thank you for reporting!
Fixed in 2.0.8.
