### ISSUE TITLE
python-colorama in epel7

### ISSUE THREAD

**Issue by evgkrsk** [strizhechenko/netutils-linux#162]
Смог запустить top-утилиты под centos7+epel только после приложения указанного патча:

```patch
diff --git netutils_linux_monitoring/base_top.py netutils_linux_monitoring/base_top.py
index 599bdb0..a01875a 100644
--- netutils_linux_monitoring/base_top.py
+++ netutils_linux_monitoring/base_top.py
@@ -6,6 +6,10 @@ from random import randint
 from time import sleep
 
 from colorama import Fore
+try:
+    BLACK = Fore.LIGHTBLACK_EX
+except AttributeError:
+    BLACK = Fore.BLACK
 from six import print_
 
 from netutils_linux_monitoring.colors import wrap
@@ -16,7 +20,7 @@ class BaseTop(object):
     current = None
     previous = None
     diff = None
-    header = wrap("Press CTRL-C to exit...\n", Fore.LIGHTBLACK_EX)
+    header = wrap("Press CTRL-C to exit...\n", BLACK)
     options = None
     file_arg = None
     file_value = None
```

Причина полагаю в тухлости python-colorama в epel7 (даже старее, чем в epel6). Проблем при работе утилит вроде бы не заметил. Понятно, что решение не идеально - неизвестно заранее, лучше ли выбрать черный или белый цвет как запасной, но мне кажется для top-утилит это некритично, Ctrl+C нажать можно и догадаться.

**Comment by strizhechenko** [comment]
Огого. Спасибо за информацию и патчик! Вообще тут ещё два решения:

1. Такого рода коду лучше быть где-нибудь в https://github.com/strizhechenko/netutils-linux/blob/14677825bb44205328900ac549a8b861ac817cde/netutils_linux_monitoring/colors.py (там уже есть подобный костыль для жёлтого цвета)
2. Попробую поковыряться в истории версий colorama, может правильнее будет указать в зависимостях версию, начиная с которой всё хорошо работает. Хотя последний вариант добавляет работы в https://github.com/strizhechenko/netutils-linux/issues/159

**Comment by strizhechenko** [comment]
Пошёл по первому пути, код в master ветке, когда мой ноутбук починят залью на pypi версию 2.5.1.

**Comment by strizhechenko** [comment]
Выпустил уже 2.5.3
