### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by strizhechenko** [strizhechenko/netutils-linux#166]
Hacktoberfest is here!

If you're know something about linux networking stack and basic architecture things like sockets/cpus/NUMA you're very welcome to help with [hacktoberfest issues](https://github.com/search?utf8=✓&q=repo%3Astrizhechenko%2Fnetutils-linux+state%3Aopen+label%3Ahacktoberfest&type=Issues)! (and others too)

**Comment by abhi281998** [comment]
Hi, I am a linux kernel developer and I write device drivers. I have a sound knowledge of linux architecture. I would like to volunteer to help in the issues.

**Comment by strizhechenko** [comment]
Hi! I would appreciate your help!
This project is more about python/settings automation, but I think the best issue you can help me with is https://github.com/strizhechenko/netutils-linux/issues/164

About rss-ladder: https://github.com/strizhechenko/netutils-linux#rss-ladder
