### ISSUE TITLE
server-info: cat: /proc/scsi/scsi: No such file or directory

### ISSUE THREAD

**Issue by divanikus** [strizhechenko/netutils-linux#183]
This message appears with both commands on Debian Linux 8.x on a physical host.

**Comment by strizhechenko** [comment]
Can you send me `uname -a` output?

**Comment by divanikus** [comment]
Linux master0 4.9.0-0.bpo.3-amd64 #1 SMP Debian 4.9.30-2+deb9u5~bpo8+1 (2017-09-28) x86_64 GNU/Linux

**Comment by strizhechenko** [comment]
BTW, don't you know, is this bug reproducible on VMs?

**Comment by divanikus** [comment]
I guess it is hardware dependent. Looks like mine machine just doesn't have scsi subsystem. VM usually do have scsi.

**Comment by divanikus** [comment]
It might be a debian thing: https://www.linuxquestions.org/questions/debian-26/squeeze-cat-proc-scsi-scsi-no-such-file-or-directory-805890/

**Comment by strizhechenko** [comment]
We don't really need it. Maybe it's a dead code since I found `lsblk` util. Fixed [here](https://github.com/strizhechenko/netutils-linux/commit/d468d32d58642344f915683f97052f52cf8a5e1e), will be available in 2.7.2 release.
