### ISSUE TITLE
cpu_count in autorps

### ISSUE THREAD

**Issue by orx0r** [strizhechenko/netutils-linux#3]
https://github.com/strizhechenko/netutils-linux/blob/master/utils/autorps#L13

А чем плох например `nproc`?
```bash
cpu_count="$(nproc)"
```

**Comment by strizhechenko** [comment]
А, кстати, вполне себе неплохой вариант, просто не знал о нем. Спасибо!

**Comment by strizhechenko** [comment]
Добавил :)

**Comment by orx0r** [comment]
Я же наоборот, не втыкаю, что здесь происходит, но про команду знаю)
Удобно например исходнички так собирать:
```bash
make -j$(nproc) && make install
```
